#!/bin/sh
# Start/stop the alarmserver daemon.
#
### BEGIN INIT INFO
# Provides:          alarmclient
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: introscop alarm client
# Description:       this program connect to server and after pushing the internal button
#                    send print screen image and alarm info
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/alarm-client
PIDFILE=/var/run/alarm-client.pid
DESC="alarm-client daemon"
NAME=alarm-client
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0




case "$1" in
start)	log_daemon_msg "Starting alarm-client daemon"
        start_daemon -p $PIDFILE $DAEMON
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping alarm-client daemon"
        kill -9 $(cat $PIDFILE)
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting alarm-client daemon" 
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/alarm-client {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0